# database config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elite
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8000
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: beishan
    keyStoreType: PKCS12
    keyAlias: tomcat