# database config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elite
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8443
  httpPort: 8080
  openSSL: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
permission:
  user-key: 123456