# database config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elite
    username: root
    password: 123456
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: update
  redis:
    database: 0
    # Redis服务器地址
    host: 39.107.112.34
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Redis*asd7bgm*we
    #连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
server:
  port: 8443
  httpPort: 8080
  openSSL: true
  ssl:
    key-store: classpath:https/keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
permission:
  user-key: 123456
# 是否初始化的时候清空redis 方法缓存
#method_cache:
#  init-clear: false
