elite:
  config:
    idcenterid: 0001
server:
  port: 8000
spring:
  profiles:
    active: dev
mybatis:
  type-aliases-package: com.gproom.elite.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:sqlmap/*.xml