# database config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elite
    username: root
    password: makelite
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8443
  httpPort: 8080
  ssl:
    key-store: classpath:214475137930308.pfx
    key-store-password: 214475137930308
    keyStoreType: PKCS12