# database config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elite
    username: root
    password: makelite
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    # Redis服务器地址
    host: 39.107.112.34
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Redis*asd7bgm*we
    #连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
server:
  port: 443
  httpPort: 80
  openSSL: true
  ssl:
    key-store: classpath:https/214475137930308.pfx
    key-store-password: 214475137930308
    keyStoreType: PKCS12